[project]
name = "secops-mcp-server"
version = "0.1.0"
description = "GitGuardian MCP server for SecOps with comprehensive security tools"
authors = [
    {name = "Clément Tourrière", email = "clement.tourriere@gitguardian.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=0.2.0",
    "httpx>=0.24.0",
    "pydantic>=2.0.0",
    "gg-api-core"
]

[project.scripts]
mcp-server = "secops_mcp_server.server:mcp.run"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
